In [1]:
import numpy as np

a = np.arange(15)

In [2]:
a.shape

(15,)

In [3]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
b  = np.reshape(a, (3, 5))

In [5]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:

b.sum(axis=1)

array([10, 35, 60])

## create random number

In [7]:
rng = np.random.default_rng()

In [8]:
rng.random()

0.3215033804195907

## generate random int list

In [9]:
lst = np.random.randint(low=0, high=10, size=5)

In [10]:
lst

array([4, 6, 2, 6, 2])

In [11]:
order = np.argsort(lst)
order

array([2, 4, 0, 1, 3], dtype=int64)

In [12]:
order = order[:3]
order

array([2, 4, 0], dtype=int64)

In [13]:
np.take_along_axis(np.arange(2, 15), order, axis=0)

array([4, 6, 2])

In [14]:
lst = np.array([2, 2, 1, 1, 3])
unique, counts = np.unique(lst, return_counts=True)
print(unique)
print(counts)
predict = np.argmax(counts)
print(unique[predict])

[1 2 3]
[2 2 1]
1


In [15]:
a = np.arange(15).reshape(3, 5)
b = np.arange(10).reshape(2, 5)

In [16]:
a @ b.T

array([[ 30,  80],
       [ 80, 255],
       [130, 430]])

In [17]:
a = np.arange(2).reshape(2, 1)
b = np.arange(3)
c = np.arange(6).reshape(2, 3)

In [18]:
c -a -b

array([[0, 0, 0],
       [2, 2, 2]])

In [23]:
lst = ['a', 'b', 'c']
for test_index, test in enumerate(lst):
    train = lst
    train.pop(test_index)
    print(train)
    print(test_index)


['b', 'c']
0
['b']
1
